### PR TITLE
Fix: RA GUI layout (CSS align, SDA bug, Search improv)

### PR DESCRIPTION
**Pull request by dcarella**
OLD REF: PR #551

**Changes > Make New Request (CSS align):**
- CSS horizontal align for 'Make New Request' page (like PR #512): for Token, Name Constraint Attributes, Other Certificate Data, and Other Data
- Bug: when only "Name Constraints, Excluded" is checked without "Name Constraints, Permitted", the title "Name Constraint Attributes" is not displayed
- Better CSS usage: modify HTML source (with adding style, and div) is better than modify CSS style. So I revert a part of my own CSS contribution (PR #512)
- now the CSS is more clear, with less default override, and more readability. So, now it's easier to override '`ra.css`'
- H3 in bold is really better, and more readable. I just removed the override from the CSS '`w_e_style.css`' (and keep the default bold feature from '`ra.css`')
- when I had added the tags '`<h:panelGroup>...<h:panelGroup/>`', I didn't indent the content for better review of the code
**QA:** don't hesitate to test with all Key-pair generation types (By the CA, Provided by user, and Postpone).

**Changes > View/Edit End Entity (SDA bug):**
- in View End Entity: Subject Directory Attributes (SDA) display is broken because the previous display (_i.e._ SSH options) is bugged
- in Edit End Entity: Subject Directory Attributes (SDA) display is broken because the CSS rules doesn't match, because there is an additional '`span`' tag

**Changes > Edit End Entity (Select list fix, CSS align):**
- in Edit End Entity: all Select lists have a fixed width which is too narrow (width forced to 'auto' is better for readability)
- enlarge all text inputs (like PR #512)
- align textarea inputs

**Changes > Search for Certificates/End Entities (improvement):**
- fix some regressions from "Edit End Entity" (Select lists)
- in Search for Certificates: the display of date options are now better
- in Search for End Entities: the display of date options are now better

### CODE REVIEW

**Comment by primetomas** [comment]
Doing some testing I found this alignement issue with SSH principal.
Screenshot from 2024-08-18 16-57-44

**Comment by dcarella** [comment]
Good catch. Thank you. Layout for SSH certificate is fixed.
I also fixed the layout of the field "Custom values" (for custom certificate validity)

**Comment by primetomas** [comment]
It looks better. But it is a little bit off, isn't it?
Screenshot from 2024-08-29 09-35-33

**Comment by primetomas** [comment]
Another issue, which was since before and not due to this patch (but perhaps you know how to fix it). Is that is "certificate subtype" is not displayed (due to a single choice in the EE profile) the key gen options are too high.
Screenshot from 2024-08-29 09-41-34

**Comment by dcarella** [comment]
Hi Tomas,
For SSH certificate, the offset is normal, because the block "SSH Certificate principals" is inside two DIVs. This block can contains several Principals (displayed by a loop "for").
I had tried to add a new title "SSH Certificate other data" at the top of the fields "Source Address", "Source Command", and "Verify Required", in order to add offset for these fields too, but the result was not really good, and could be confusing.
In all Make Request form, they are several offsets due to this technical double DIVs. The effort to fix it (by doubling all the single DIVs) is too heavy in the source code, and by time to send, comparing to the result obtained.
I propose you to keep it as that.

**Comment by dcarella** [comment]
Tomas,
For the bug of the Certificate subtype, I will make tests.

**Comment by dcarella** [comment]
The bug with the Select Request Template had been fixed (works well in Firefox, and Chrome)

**Pull request merged**
