### PR TITLE
L10n: Localize RA GUI in French (based on 8.2.0) Fully translated

### PR DESCRIPTION
**Pull request by dcarella**
Full localization of RA GUI in French.

### CODE REVIEW

**Comment by primetomas** [comment]
@dcarella : Can you squash these commits for me? That makes it much easier to apply to the internal Enterprise repo.

**Comment by dcarella** [comment]
All commits has been squashed, and pushed to the repository (in this PR)

**Comment by primetomas** [comment]
It's listed as 7 comitts above so it doens't look squashed. Downloading the patch:
curl -s https://patch-diff.githubusercontent.com/raw/Keyfactor/ejbca-ce/pull/572.patch --output /tmp/ce-patch
shows multiple change comitts to modules/ra-gui/resources/WEB-INF/classes/Messages_fr.properties. 
I think the merge commits makes it hard to apply this patch on another repo.

**Comment by primetomas** [comment]
I'll just transfer the whole files instead. 

There is a bug in "menu_pagetitle_loggedin"

**Comment by dcarella** [comment]
I'll make a new PR (bis)
I'll check the bug

**Comment by dcarella** [comment]
PR #581 - with one unique commit. ;-)
Thank you for your patience!

**Pull request closed without merging**
