### PR TITLE
Improvement: Refactor standard PKIX Document-Signing EKU

### PR DESCRIPTION
**Pull request by dcarella**
The general Document-Signing purposes come from PKI X.509 Working Group, cf. RFC 9336.
Then, as all PKIX EKU, such as 'Code Signing', 'Time Stamping', 'SIP Domain', 'SSH Client', etc., there is not need to specify the RFC number.
For vendor-specific, we had prefixed these EKUs with the vendor abbreviation, e.g. 'MS', 'ICAO', etc.
But, for all standard EKU, we don't add 'PKIX', neither 'X.509', neither 'RFC' reference.

Ref.: https://datatracker.ietf.org/doc/html/rfc9336

### CODE REVIEW

**Comment by dcarella** [comment]
Thank you for your right remark.
I had reverted all languages, but French one.
In all languages, I had copied the "MS Document Signing" message, and I had replaced "MS" by "RFC9336".
In French, there is no doubt about "Document Signing", because I always keep the English label for vendor messages (e.g. for MS, Adobe, Intel, etc.) with a simple description of the functionality in parentheses. Whereas, for PKIX standard EKU, I had translated all messages in French (as "Signature de ..."), and I always had added the EKU official technical name in parentheses (e.g. codeSigning, OCSPSigning, and documentSigning).
And for this EKU in French, I had added the "RFC9336" in brackets, to prevent any confusion.

**Comment by dcarella** [comment]
Hi Tomas,
This PR is it ready for merging?
Or, I need to fix something else?
David

**Comment by primetomas** [comment]
I think it's ready, I just didn't get time to review and merge it :-(

**Comment by primetomas** [comment]
There is a bug in this PR. It does not work for upgrades. If you upgrade an existing installation, the string visible in System Configuration->Extended Key Usages show EKU_DOCUMENT_SIGNING_RFC9336, because the language string is in system configuration due to UpgradeSessionBean already been run.
Screenshot from 2023-10-08 09-18-36

**Comment by dcarella** [comment]
There are two fixes possible:
1. In "System Configuration->Extended Key Usages", click "Remove", then add a new EKU "1.3.6.1.5.5.7.3.36" / "EKU_PKIX_DOCUMENTSIGNING", then the right message will be displayed in CA GUI ; of course, this case needs to add this process in UPGRADE doc,
2. Put back the message "EKU_DOCUMENT_SIGNING_RFC9336" in language files for backward compatibility, and always keep the new message "EKU_PKIX_DOCUMENTSIGNING" too. In this case, the new installation use the new message key, and old installation find the right message behind the old message key.

The #1 is the cleanest (for code, no old code to keep): it's my preferred.
The #2 is the easiest for the user, because there is nothing to do!

**Comment by primetomas** [comment]
EJBCA have thousands of users, requiring all of them to make a manual re-configuration in the Admin UI is not an option. "Never break an existing installation" is a rule that we need to try to follow as long as possible.

Therefore no 2 is the only option that can work in my opinion.

**Comment by dcarella** [comment]
Fixed according to n° 2.
Ready for testing

**Pull request merged**
